### ISSUE TITLE
DialogDemo.java don't start

### ISSUE THREAD

**Issue by Deycsays** [cmusphinx/sphinx4#50] opened 2016-02-07 13:38 UTC
I just start DialogDemo.java and get exception:

```
Exception in thread "main" java.lang.IllegalStateException: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at edu.cmu.sphinx.api.Microphone.<init>(Microphone.java:38)
	at edu.cmu.sphinx.api.SpeechSourceProvider.getMicrophone(SpeechSourceProvider.java:18)
	at edu.cmu.sphinx.api.LiveSpeechRecognizer.<init>(LiveSpeechRecognizer.java:35)
	at edu.cmu.sphinx.demo.dialog.DialogDemo.main(DialogDemo.java:145)
Caused by: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(Unknown Source)
	at com.sun.media.sound.AbstractDataLine.open(Unknown Source)
	at com.sun.media.sound.AbstractDataLine.open(Unknown Source)
	at edu.cmu.sphinx.api.Microphone.<init>(Microphone.java:36)
	... 3 more
```
I don't sure that it was a bug.

**Comment by nshmyrev** [comment] 2016-02-07 14:14
Duplicate of https://github.com/cmusphinx/sphinx4/issues/33

**Closed by nshmyrev** 2016-02-07 14:14 UTC
